# Generated by Django 5.0.6 on 2024-05-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='users.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.CharField(choices=[('FINANCE', 'Finance'), ('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager')], default='EMPLOYEE', max_length=50),
        ),
    ]
