# Generated by Django 5.0.6 on 2024-05-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_manager_id_alter_employee_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='postal_code',
            new_name='postcode',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='admin@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_code',
            field=models.CharField(default='0123456789', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance')], default='EMPLOYEE', max_length=50),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
