# Generated by Django 5.0.6 on 2024-05-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_employee_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('EMPLOYEE', 'Employee'), ('FINANCE', 'Finance')], default='EMPLOYEE', max_length=50),
        ),
    ]
