# Generated by Django 5.0.6 on 2024-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_finance_id_alter_employee_manager_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('FINANCE', 'Finance')], default='EMPLOYEE', max_length=50),
        ),
    ]
