# Generated by Django 5.0.6 on 2024-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_employee_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='permission',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('FINANCE', 'Finance'), ('MANAGER', 'Manager')], default='EMPLOYEE', max_length=50),
        ),
    ]
