# Generated by Django 5.0.6 on 2024-05-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REJECTEDF', 'Rejectedf')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('GIFT', 'Gift'), ('ACCOMMODATION', 'Accommodation'), ('MEAL', 'Meal'), ('OTHER', 'Other'), ('TRAVEL', 'Travel')], max_length=50),
        ),
    ]
