# Generated by Django 5.0.6 on 2024-05-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_status_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='receipt',
            field=models.FileField(null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTEDF', 'Rejectedf'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('TRAVEL', 'Travel'), ('GIFT', 'Gift'), ('ACCOMMODATION', 'Accommodation'), ('MEAL', 'Meal'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
