# Generated by Django 5.0.6 on 2024-05-17 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_receipt_alter_claim_status_and_more'),
        ('users', '0006_alter_employee_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='finance_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='finance', to='users.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='manager_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.RESTRICT, related_name='manager', to='users.employee'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('REJECTEDF', 'Rejectedf'), ('PROCESSED', 'Processed'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('MEAL', 'Meal'), ('GIFT', 'Gift'), ('TRAVEL', 'Travel'), ('ACCOMMODATION', 'Accommodation')], max_length=50),
        ),
    ]
