# Generated by Django 5.0.6 on 2024-05-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_claim_finance_id_claim_manager_id_alter_claim_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='finance_id',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='manager_id',
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('REJECTEDF', 'Rejectedf'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('GIFT', 'Gift'), ('MEAL', 'Meal'), ('ACCOMMODATION', 'Accommodation'), ('TRAVEL', 'Travel'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
