# Generated by Django 5.0.6 on 2024-05-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_alter_claim_status_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTEDF', 'Rejectedf'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('GIFT', 'Gift'), ('MEAL', 'Meal'), ('OTHER', 'Other'), ('TRAVEL', 'Travel'), ('ACCOMMODATION', 'Accommodation')], max_length=50),
        ),
    ]
