# Generated by Django 5.0.6 on 2024-05-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_alter_claim_status_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTEDF', 'Rejectedf'), ('REJECTED', 'Rejected'), ('PROCESSED', 'Processed'), ('APPROVED', 'Approved')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('OTHER', 'Other'), ('ACCOMMODATION', 'Accommodation'), ('TRAVEL', 'Travel'), ('GIFT', 'Gift'), ('MEAL', 'Meal')], max_length=50),
        ),
    ]
