# Generated by Django 5.0.6 on 2024-05-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_alter_claim_status_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSED', 'Processed'), ('REJECTEDF', 'Rejectedf')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('ACCOMMODATION', 'Accommodation'), ('OTHER', 'Other'), ('TRAVEL', 'Travel'), ('GIFT', 'Gift'), ('MEAL', 'Meal')], max_length=50),
        ),
    ]
