# Generated by Django 5.0.6 on 2024-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_alter_claim_status_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Processed'), ('REJECTED', 'Rejected'), ('REJECTEDF', 'Rejectedf'), ('PENDING', 'Pending'), ('APPROVED', 'Approved')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('Gift', 'Gift'), ('Meal', 'Meal'), ('Other', 'Other'), ('Night stay', 'Night stay'), ('Travel', 'Travel')], max_length=50),
        ),
    ]
