# Generated by Django 5.0.6 on 2024-05-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_alter_claim_status_alter_claim_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('REJECTEDF', 'Rejectedf'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('Other', 'Other'), ('Travel', 'Travel'), ('Meal', 'Meal'), ('Night stay', 'Night stay'), ('Gift', 'Gift')], max_length=50),
        ),
    ]
